# ControlBans Configuration
# Advanced punishment system with LiteBans compatibility
# Version: 1.0.0

# Database Configuration
database:
  # Database type: mysql, mariadb, postgresql, sqlite
  type: sqlite

  # Database connection details (not needed for SQLite)
  host: localhost
  port: 3306
  database: controlbans
  username: root
  password: password

  # SQLite file location (relative to plugin data folder)
  sqlite-file: punishments.db

  # Connection pool settings
  pool:
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 300000
    max-lifetime: 1800000

# Alt Account Punishment
alts-punish:
  # Enable automatic punishment of alternate accounts
  enabled: false

  # Punishment types to apply to alts
  apply-to:
    bans: true
    tempbans: false
    mutes: false

  # Safety features
  safety:
    # Minimum confidence level for alt detection (0.0-1.0)
    min-confidence: 0.8
    # Maximum alts to punish at once
    max-alts: 5
    # Cooldown between alt punishments (seconds)
    cooldown: 300

  # Logging
  log-alt-punishments: true
  notify-staff: true

# Web Interface
web:
  # Enable built-in web viewer
  enabled: false

  # Server configuration
  host: 0.0.0.0
  port: 8080

  # Security
  admin-token: change-me-please
  allowed-hosts:
    - localhost
    - 127.0.0.1

  # SSL/TLS (requires certificate files)
  tls:
    enabled: false
    keystore-path: keystore.jks
    keystore-password: password

  # Web interface settings
  records-per-page: 50
  auto-refresh-interval: 30

# Integration Settings
integrations:
  # DiscordSRV Integration
  discord:
    enabled: false

    # Channel IDs for different punishment types
    channels:
      bans: "ban-logs"
      unbans: "unban-logs"
      mutes: "mute-logs"
      warns: "warn-logs"
      kicks: "kick-logs"

    # Message formatting
    embed-color:
      ban: 16711680      # Red
      unban: 65280       # Green
      mute: 16776960     # Yellow
      warn: 16753920     # Orange
      kick: 12632256     # Purple

    # Include additional information
    include-duration: true
    include-reason: true
    include-staff: true

  # Geyser/Floodgate Integration
  geyser:
    enabled: false

    # Handle Bedrock player UUIDs properly
    bedrock-uuid-handling: true

    # Bedrock-specific punishment messages
    bedrock-messages:
      use-custom: false

  # MCBlacklist Integration
  mcblacklist:
    enabled: false

    # Firebase URL
    firebase-url: "https://mcblacklistdb-default-rtdb.firebaseio.com/players.json"

    # Check frequency (minutes)
    check-interval: 60

    # Action on blacklisted player
    action: ban  # ban, kick, warn
    reason: "Player found on MCBlacklist database"

    # Auto-update blacklist
    auto-update: true

# Import Settings
import:
  # Progress reporting interval (records processed)
  progress-interval: 1000

  # Batch size for database operations
  batch-size: 500

  # Timeout for import operations (seconds)
  timeout: 3600

  # Backup before import
  create-backup: true

# Punishment Settings
punishments:
  # Default reasons
  default-reasons:
    ban: "Unspecified"
    mute: "Unspecified"
    warn: "Unspecified"
    kick: "Disconnected"

  # Maximum punishment duration (for non-admins)
  max-duration:
    tempban: 2592000  # 30 days in seconds
    tempmute: 604800  # 7 days in seconds

  # Punishment broadcast settings
  broadcast:
    enabled: true

    # Broadcast to console
    console: true

    # Broadcast to players with permission
    players: true

    # When true, all punishments will be silent (staff-only) unless the -s flag is used to make them public.
    # When false (default), punishments are public unless the -s flag is used to make them silent.
    silent-by-default: false

# Cache Settings
cache:
  # Enable caching for performance
  enabled: true

  # Cache TTL (seconds)
  ttl:
    player-lookup: 300
    punishment-check: 60
    alt-lookup: 600

  # Maximum cache size
  max-size: 10000

  # Clear cache on punishment changes
  clear-on-change: true

# Performance Settings
performance:
  # Use async database operations
  async-database: true

  # Connection validation
  validate-connections: true

  # Query timeout (seconds)
  query-timeout: 30

  # Enable debug logging
  debug-logging: false

# Time Format
time-format:
  # Date format for displays
  date-format: "yyyy-MM-dd HH:mm:ss"

  # Timezone (default: server timezone)
  timezone: "UTC"

  # Duration parsing
  duration-units:
    s: seconds
    m: minutes
    h: hours
    d: days
    w: weeks
    mo: months
    y: years

# Messages
messages:
  # Prefix for all plugin messages
  prefix: "&8[&cControlBans&8] &7"

  # Error messages
  errors:
    no-permission: "&cYou don't have permission to use this command."
    player-not-found: "&cPlayer '%player%' not found."
    player-not-banned: "&cPlayer '%player%' is not banned."
    player-not-muted: "&cPlayer '%player%' is not muted."
    player-offline: "&cPlayer '%player%' is not online."
    invalid-duration: "&cInvalid duration format. Use: 1d2h3m4s"
    invalid-arguments: "&cInvalid arguments. Usage: %usage%"
    database-error: "&cDatabase error occurred. Please try again."
    import-failed: "&cImport failed: %error%"

  # Success messages
  success:
    ban: "&aSuccessfully banned &c%player%&a."
    tempban: "&aSuccessfully temporarily banned &c%player% &afor &c%duration%&a."
    unban: "&aSuccessfully unbanned &c%player%&a."
    mute: "&aSuccessfully muted &c%player%&a."
    tempmute: "&aSuccessfully temporarily muted &c%player% &afor &c%duration%&a."
    unmute: "&aSuccessfully unmuted &c%player%&a."
    warn: "&aSuccessfully warned &c%player%&a."
    kick: "&aSuccessfully kicked &c%player%&a."
    import-complete: "&aImport completed successfully. Imported &c%count% &arecords."

  # Broadcast messages
  punishments:
    broadcast:
      format:
        ban: "&b&lPunishment &7(Ban) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        tempban: "&b&lPunishment &7(Temp-Ban) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        unban: "&a&lPunishment &7(Unban) &8» &fPlayer &b{player} &fwas unbanned by &b{staff}"
        mute: "&b&lPunishment &7(Mute) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        tempmute: "&b&lPunishment &7(Temp-Mute) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        unmute: "&a&lPunishment &7(Unmute) &8» &fPlayer &b{player} &fwas unmuted by &b{staff}"
        warn: "&b&lPunishment &7(Warn) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        kick: "&b&lPunishment &7(Kick) &8» &fPlayer &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"
        ipban: "&b&lPunishment &7(IP-Ban) &8» &fIP &b{player}&f, Punished by &b{staff}&f, Reason &b{reason}"

  # Customizable disconnect/kick screens and messages
  screens:
    ban:
      - ""
      - "&bYou're banned from this server!"
      - "&7&oPunishment ID: {id}"
      - ""
      - "&3● &bBanned on &f» &3{date}"
      - "&3● &bBanned by &f» &3{staff}"
      - "&3● &bReason &f» &3{reason}"
      - ""
      - "&a✔ &2Expiry Date &f» &aNever"
      - "&d✉ &5Appeal &f» &dappeal.servername.com"
      - ""
    tempban:
      - ""
      - "&bYou're temporarily banned from this server!"
      - "&7&oPunishment ID: {id}"
      - ""
      - "&3● &bBanned on &f» &3{date}"
      - "&3● &bBanned by &f» &3{staff}"
      - "&3● &bReason &f» &3{reason}"
      - ""
      - "&e✔ &6Expiry Date &f» &e{duration}"
      - "&d✉ &5Appeal &f» &dappeal.servername.com"
      - ""
    ip_ban:
      - ""
      - "&c&lYour IP has been banned from this server!"
      - "&7&oPunishment ID: {id}"
      - ""
      - "&4● &cBanned by &f» &4{staff}"
      - "&4● &cReason &f» &4{reason}"
      - ""
      - "&a✔ &2Expiry Date &f» &aNever"
      - "&d✉ &5Appeal &f» &dappeal.servername.com"
      - ""
    ip_tempban:
      - ""
      - "&c&lYour IP has been temporarily banned!"
      - "&7&oPunishment ID: {id}"
      - ""
      - "&4● &cBanned by &f» &4{staff}"
      - "&4● &cReason &f» &4{reason}"
      - ""
      - "&e✔ &6Expiry Date &f» &e{duration}"
      - "&d✉ &5Appeal &f» &dappeal.servername.com"
      - ""
    kick:
      - ""
      - "&cYou were kicked from the server!"
      - "&7&oPunishment ID: {id}"
      - ""
      - "&6⏵ &eReason &f» &6{reason}"
      - "&6⏵ &eKicked by &f» &6{staff}"
      - ""
    mute:
      - "&b&lYou have been muted! &7(Permanent) &7&oID: {id}"
      - "&3● &bMuted by &f» &3{staff}"
      - "&3● &bReason &f» &3{reason}"
      - "&3● &bExpires In &f» &3Never"
    tempmute:
      - "&b&lYou have been muted! &7&oID: {id}"
      - "&3● &bMuted by &f» &3{staff}"
      - "&3● &bReason &f» &3{reason}"
      - "&3● &bExpires In &f» &3{duration}"
    ip_mute:
      - "&c&lYour IP address has been muted! &7(Permanent) &7&oID: {id}"
      - "&4● &cMuted by &f» &4{staff}"
      - "&4● &cReason &f» &4{reason}"
      - "&4● &cExpires In &f» &4Never"
    ip_tempmute:
      - "&c&lYour IP address has been muted! &7&oID: {id}"
      - "&4● &cMuted by &f» &4{staff}"
      - "&4● &cReason &f» &4{reason}"
      - "&4● &cExpires In &f» &4{duration}"
    warn:
      - ""
      - "&e&lYou have received a warning! &7&oID: {id}"
      - "&6⏵ &eWarned by &f» &6{staff}"
      - "&6⏵ &eReason &f» &6{reason}"
      - ""