name: ControlBans
version: 3.1
main: ret.tawny.controlbans.ControlBansPlugin
description: Advanced punishment system with LiteBans compatibility
api-version: "1.20"
author: Tawny
folia-supported: true

softdepend:
  - DiscordSRV
  - Floodgate
  - voicechat

commands:
  ban:
    description: Ban a player permanently
    usage: /ban [-s] <player> [reason]
    permission: controlbans.ban
    aliases: [b]
  tempban:
    description: Temporarily ban a player
    usage: /tempban [-s] <player> <time> [reason]
    permission: controlbans.tempban
    aliases: [tban, tb]
  unban:
    description: Unban a player or IP
    usage: /unban [-s] <player|ip>
    permission: controlbans.unban
    aliases: [pardon]
  mute:
    description: Mute a player permanently
    usage: /mute [-s] <player> [reason]
    permission: controlbans.mute
    aliases: [m]
  tempmute:
    description: Temporarily mute a player
    usage: /tempmute [-s] <player> <time> [reason]
    permission: controlbans.tempmute
    aliases: [tmute, tm]
  unmute:
    description: Unmute a player
    usage: /unmute [-s] <player>
    permission: controlbans.unmute
  warn:
    description: Warn a player
    usage: /warn [-s] <player> [reason]
    permission: controlbans.warn
    aliases: [w]
  kick:
    description: Kick a player
    usage: /kick [-s] <player> [reason]
    permission: controlbans.kick
    aliases: [k]
  history:
    description: View player punishment history
    usage: /history <player>
    permission: controlbans.history
    aliases: [h, punishments]
  check:
    description: Check if a player is banned/muted
    usage: /check <player>
    permission: controlbans.check
    aliases: [c]
  alts:
    description: View alternate accounts for a player
    usage: /alts <player>
    permission: controlbans.alts
    aliases: [alt]
  appeal:
    description: Submit an appeal for an active mute
    usage: /appeal <message>
    permission: controlbans.appeal
  controlbans:
    description: Main ControlBans command for admin tasks like imports and reloads
    usage: /controlbans <import|reload>
    permission: controlbans.admin
    aliases: [cb]
  ipban:
    description: Ban all accounts associated with an IP address.
    usage: /ipban [-s] <player|ip> <time> [reason]
    permission: controlbans.ban.ip
    aliases: [iban]
  ipmute:
    description: Mute all accounts associated with an IP address.
    usage: /ipmute [-s] <player|ip> <time> [reason]
    permission: controlbans.mute.ip
    aliases: [imute]
  voidjail:
    description: Send a player to the void jail.
    usage: /voidjail <player>
    permission: controlbans.voidjail
    aliases: [vjail]
  unvoidjail:
    description: Release a player from the void jail.
    usage: /unvoidjail <player>
    permission: controlbans.voidjail
    aliases: [unvjail]
  banskin:
    description: Removes a player's skin, forcing the default skin.
    usage: /banskin <player> [reason]
    permission: controlbans.banskin
  unbanskin:
    description: Restores a player's ability to use their custom skin.
    usage: /unbanskin <player>
    permission: controlbans.banskin
  voicemute:
    description: Mute a player in voice chat.
    usage: /voicemute [-s] <player> [reason]
    permission: controlbans.voicemute
  voiceunmute:
    description: Unmute a player in voice chat.
    usage: /voiceunmute <player>
    permission: controlbans.voiceunmute

permissions:
  controlbans.*:
    description: Access to all ControlBans commands
    children:
      controlbans.ban: true
      controlbans.tempban: true
      controlbans.unban: true
      controlbans.mute: true
      controlbans.tempmute: true
      controlbans.unmute: true
      controlbans.warn: true
      controlbans.kick: true
      controlbans.history: true
      controlbans.check: true
      controlbans.alts: true
      controlbans.appeal: true
      controlbans.admin: true
      controlbans.import: true
      controlbans.exempt: true
      controlbans.ban.ip: true
      controlbans.mute.ip: true
      controlbans.notify.silent: true
      controlbans.voidjail: true
      controlbans.banskin: true
      controlbans.voicemute: true
      controlbans.voiceunmute: true
  controlbans.ban:
    description: Permission to ban players
    default: op
  controlbans.tempban:
    description: Permission to temporarily ban players
    default: op
  controlbans.unban:
    description: Permission to unban players
    default: op
  controlbans.mute:
    description: Permission to mute players
    default: op
  controlbans.tempmute:
    description: Permission to temporarily mute players
    default: op
  controlbans.unmute:
    description: Permission to unmute players
    default: op
  controlbans.warn:
    description: Permission to warn players
    default: op
  controlbans.kick:
    description: Permission to kick players
    default: op
  controlbans.history:
    description: Permission to view punishment history
    default: op
  controlbans.check:
    description: Permission to check player punishment status
    default: op
  controlbans.alts:
    description: Permission to view alternate accounts
    default: op
  controlbans.appeal:
    description: Allows players to submit mute appeals
    default: true
  controlbans.admin:
    description: Permission for administrative commands (reload, etc.)
    default: op
  controlbans.import:
    description: Permission to import punishments
    default: op
  controlbans.exempt:
    description: Exemption from punishments
    default: false
  controlbans.ban.ip:
    description: Permission to ban by IP address.
    default: op
  controlbans.mute.ip:
    description: Permission to mute by IP address.
    default: op
  controlbans.notify.silent:
    description: Receives broadcast messages for silent punishments.
    default: op
  controlbans.voidjail:
    description: Permission to use the void jail commands.
    default: op
  controlbans.banskin:
    description: Permission to use the skin banning commands.
    default: op
  controlbans.voicemute:
    description: Permission to mute players in voice chat.
    default: op
  controlbans.voiceunmute:
    description: Permission to unmute players in voice chat.
    default: op